import { expect } from "playwright/test";
import { test } from "../../lambdatest-setup";
//import { test } from "../../browserstack-setup";


test('register and login page', async ({ page }) => {

  //Dashboard page Expect value check
  await page.goto('https://filemasterdev.enerlex.com/');
  await expect(page.getByRole('heading')).toContainText('FileMaster');
  await page.getByPlaceholder('Your Username').click();
  await page.getByPlaceholder('Your Username').fill('praneshBuyer');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('U67dQBvGdE2j');
  await page.getByRole('button', { name: 'Log In!' }).click();
  await expect(page.locator('h4')).toContainText('Overview for Pranesh');
  await expect(page.locator('#datepicker')).toHaveValue('02/13/2024');
  await expect(page.locator('body')).toContainText('1 Ready for Offer');
  await expect(page.locator('body')).toContainText('120 File Review');
  await expect(page.locator('body')).toContainText('0 My Tasks');
  // await expect(page.locator('body')).toContainText('0 Tasks');
  await expect(page.locator('body')).toContainText('120 Checked Out');
  await expect(page.locator('body')).toContainText('0 Urgent Tasks');
  await expect(page.locator('body')).toContainText('28 Deeds Pending');
  await expect(page.locator('body')).toContainText('6 Offers to Send');
  await expect(page.locator('body')).toContainText('1 Unreceived Requests');


  //search data and check file details
  await page.getByPlaceholder('Search Name or Phone...').click();
  await page.getByPlaceholder('Search Name or Phone...').fill('718-375-2652');
  await page.getByRole('button', { name: '' }).click();
  await expect(page.locator('tbody')).toContainText('Chadwick, Albert A. - FAKE');
  await expect(page.locator('tbody')).toContainText('Mandel, Geri Sima');
  await expect(page.locator('tbody')).toContainText('Aaron Stoffel');
  await expect(page.locator('tbody')).toContainText('TX');
  await expect(page.locator('tbody')).toContainText('718-375-2652');
  await page.getByRole('link', { name: 'Chadwick, Albert A. - FAKE' }).click();
  await expect(page.getByLabel('File Name:')).toHaveValue('Chadwick, Albert A. - FAKE');
  await expect(page.getByLabel('File Origin:')).toHaveValue('Unknown - Glasscock');
  await expect(page.getByLabel('Start Date:')).toHaveValue('04/28/2023');
  await expect(page.locator('body')).toContainText('File View');
  await expect(page.getByLabel('Buyer:')).toHaveValue('1');
  await expect(page.getByLabel('File Status:')).toHaveValue('Working Files');
  await expect(page.getByLabel('Paper Location:')).toHaveValue('File Room/Cabinets/Working');
  await expect(page.getByLabel('as of')).toHaveValue('04/28/2023');
  await expect(page.getByLabel('Total File Offer:')).toHaveValue('754');
  await expect(page.locator('b')).toContainText('Total File Value: $3,770.00');
  await page.getByLabel('Paper File Exists?').check();
  await expect(page.getByLabel('Paper File Exists?')).toBeChecked();
  await expect(page.locator('#CTable')).toContainText('Mandel');
  await expect(page.locator('#pills-info-tab')).toContainText('File Info');
  await expect(page.locator('#CTable')).toContainText('Geri Sima');
  await expect(page.locator('#CTable')).toContainText('Contact/Relative/MAYBE');
  await expect(page.locator('#CTable')).toContainText('0%');
  await expect(page.locator('#CTable')).toContainText('1162 E. 7th St.');

  await page.goto('https://filemasterdev.enerlex.com/editfile_buyerview.php?fileid=24333');
  await expect(page.locator('#CTable')).toContainText('Oster');
  await expect(page.locator('#CTable')).toContainText('Sherry R.');
  await expect(page.locator('#CTable')).toContainText('CONTACT/Daughter to Sarah & Leo/MAYBE');
  await expect(page.locator('#CTable')).toContainText('0%');
  await expect(page.locator('#CTable')).toContainText('1162 E. 7th St.');
  await expect(page.locator('#CTable')).toContainText('Brooklyn');

  await expect(page.getByLabel('Black Bart:')).toHaveValue('BB/Glasscock - $6,520; a/o 3/11/2014 $26,490; $7,280 (2017); $7,520 (2020); Sarah Mandel - $34,169 (2014); Sarah - $15,260 (2019); $4,820 (2021);');
  await expect(page.getByLabel('MM/Suspense:')).toHaveValue('0.00');
  await expect(page.locator('#MMComment')).toHaveValue('TX-0;');
  await expect(page.getByLabel('Current Taxes:')).toHaveValue('Glasscock - Delinquent 2004-16 & 2018/20 - $6,035.08; Sarah - 2020 - $243.98; Howard - Albert - 2017 only - $72.14; Sarah - current;');
  await expect(page.getByLabel('TX Appraised Value:')).toHaveValue('3770');
  await expect(page.locator('#TotalAppraisedValue')).toHaveValue('2021 - Albert only;    GRAND TOTAL - $8,590 (2021);');
  await expect(page.getByLabel('Online County Records Dt:')).toHaveValue('03/06/1919');
  await expect(page.getByLabel('Online Research Date:')).toHaveValue('04/28/2023');
  await expect(page.locator('#txstaterecck')).toBeChecked();
  await expect(page.locator('#pills-info')).toContainText('# of Legals: 4 Add a legal desc');
  await expect(page.locator('#pills-info')).toContainText('Edit');
  await expect(page.locator('#pills-info')).toContainText('TX');
  await expect(page.locator('#pills-info')).toContainText('Glasscock');
  await expect(page.locator('#pills-info')).toContainText('T&P RR Co');
  await expect(page.locator('#pills-info')).toContainText('2S');
  await expect(page.locator('#pills-info')).toContainText('33');
  await expect(page.locator('#pills-info')).toContainText('23');
  await expect(page.locator('#pills-info')).toContainText('110');
  await expect(page.locator('#pills-info')).toContainText('Unknown');
  await expect(page.locator('#pills-info')).toContainText('RI');
  await expect(page.locator('#pills-info')).toContainText('0.0015630000');
  await expect(page.locator('#pills-info')).toContainText('0');
  await expect(page.locator('#pills-info')).toContainText('Yes');
  await expect(page.locator('#pills-info')).toContainText('Copy');
  await expect(page.getByLabel('Notes on Legals:')).toBeEmpty();
  await expect(page.getByLabel('County:')).toHaveValue('Glasscock');
  await expect(page.getByLabel('State:')).toHaveValue('TX');
  await page.getByLabel('Box No:').click();
  await expect(page.getByLabel('Dead:')).not.toBeChecked();
  await expect(page.getByLabel('Comment:')).toBeEmpty();
  await expect(page.locator('#pills-info')).toContainText('Notes on Legals: County: State: Dead: Box No: Comment: File Last Modified By: at 06/02/2023 12:00 AM');


  //Create New Contact
  await expect(page.locator('#pills-info')).toContainText('Add a contact');
  await page.getByRole('link', { name: 'Add a contact' }).click();
  await page.getByLabel('Relation:').click();
  await page.getByLabel('Relation:').press('CapsLock');
  await page.getByLabel('Relation:').fill('B');
  await page.getByLabel('Relation:').press('CapsLock');
  await page.getByLabel('Relation:').fill('Brother');
  await page.getByLabel('Ownership:').click();
  await page.getByLabel('Ownership:').fill('50');
  await page.getByLabel('Last Name:').click();
  await page.getByLabel('Last Name:').press('CapsLock');
  await page.getByLabel('Last Name:').fill('T');
  await page.getByLabel('Last Name:').press('CapsLock');
  await page.getByLabel('Last Name:').fill('Test');
  await page.getByLabel('First Name:').click();
  await page.getByLabel('First Name:').click();
  await page.getByLabel('First Name:').fill('praneshBuyer');
  await page.getByLabel('Alternative Name:').click();
  await page.getByLabel('Alternative Name:').fill('praneshBuyer');
  await page.getByLabel('SSN:').click();
  await page.getByLabel('SSN:').fill('124536958');
  await page.locator('#deceased').check();
  await page.getByLabel('Date of Death:').click();
  await page.locator('#deceased').uncheck();
  await page.getByLabel('Date of Death:').click();
  await page.locator('#deceased').check();
  await page.getByLabel('Date of Death:').click();
  await page.getByLabel('Date of Death:').fill('12/12/2022');
  await page.getByLabel('Date of Birth:').click();
  await page.getByLabel('Date of Birth:').fill('12/12/1863');
  await page.getByLabel('Address:').click();
  await page.getByLabel('Address:').fill('brokelyn');
  await page.getByLabel('City:').click();
  await page.getByLabel('City:').fill('newyork');
  await page.getByLabel('State:').selectOption('CO');
  await page.getByLabel('Zip Code:').click();
  await page.getByLabel('Zip Code:').fill('123456');
  await page.getByLabel('Phone:').click();
  await page.getByLabel('Phone:').fill('123');
  await page.locator('#prefix').fill('154');
  await page.locator('#phoneno').fill('8522');
  await page.locator('#phonedesc').selectOption('Bad');
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').fill('divaharg180@gmail.com');
  await page.getByLabel('Note:').click();
  await page.getByLabel('Note:').fill('test');



  //create new file
  await page.goto('https://filemasterdev.enerlex.com/editfile_buyerview.php?fileid=24333');
  await expect(page.locator('#pills-info')).toContainText('Show family tree');
  await page.getByRole('link', { name: 'Show family tree' }).click();
  // await expect(page.locator('[id="\\31 707734640094126"]')).toContainText('Albert A.');
  await page.getByRole('link', { name: 'FileMaster Dashboard' }).click();
  await expect(page.getByRole('list')).toContainText('New File');
  await page.getByRole('link', { name: ' New File' }).click();
  await expect(page.locator('body')).toContainText('Create New File');
  await page.getByLabel('File Name:').click();
  await page.getByLabel('File Name:').fill('praneshBuyer');
  await page.getByLabel('File Origin:').click();
  await page.getByLabel('File Origin:').fill('praneshBuyer');
  await page.getByLabel('Start Date:').click();
  await page.getByRole('cell', { name: '12' }).click();
  await page.getByLabel('Legals County:').click();
  await page.getByLabel('Legals County:').fill('newyork');
  await page.getByLabel('Legals State:').click();
  await page.getByLabel('Legals State:').fill('newyork');
  await page.getByLabel('MM/Suspense:').click();
  await page.getByLabel('MM/Suspense:').fill('120');
  await page.getByPlaceholder('Comment').click();
  await page.getByPlaceholder('Comment').fill('test');
  await page.getByLabel('Online Research Dt:').click();
  await page.getByRole('cell', { name: '13' }).click();
  await page.getByLabel('File Status:').selectOption('Ready for Offer');
  await page.getByLabel('File Location:').selectOption('Sterling');
  await page.getByLabel('Relation:').click();
  await page.getByLabel('Relation:').fill('brother');
  await page.getByLabel('Ownership:').click();
  await page.getByLabel('Ownership:').fill('100');
  await page.getByLabel('Last Name:').click();
  await page.getByLabel('Last Name:').fill('praneshBuyer');
  await page.getByLabel('First Name:').click();
  await page.getByLabel('First Name:').fill('praneshBuyer');
  await page.getByLabel('Alternative Name:').click();
  await page.getByLabel('Alternative Name:').fill('praneshBuyer');
  await page.getByLabel('SSN:').click();
  await page.getByLabel('SSN:').fill('123456885');
  await page.locator('#deceased').check();
  await page.getByLabel('Date of Death:').click();
  await page.getByLabel('Date of Death:').click();
  await page.getByLabel('Date of Death:').fill('12/12/2023');
  await page.getByLabel('Date of Birth:').click();
  await page.getByLabel('Date of Birth:').fill('12/12/1863');
  await page.getByLabel('Address:').click();
  await page.getByLabel('Address:').fill('newyork');
  await page.getByLabel('City:').click();
  await page.getByLabel('City:').fill('newyork');
  await page.getByLabel('State:', { exact: true }).selectOption('FL');
  await page.getByLabel('Zip Code:').click();
  await page.getByLabel('Zip Code:').fill('123456');
  await page.getByLabel('Phone:').click();
  await page.getByLabel('Phone:').fill('123');
  await page.locator('#prefix').fill('585');
  await page.locator('#phoneno').fill('2255');
  await page.locator('#phonedesc').selectOption('Relative');
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').fill('divaharg180@gmail.com');


});